services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: items
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - items
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    environment:
      PORT: 3000
      NODE_ENV: development
      DB_USER: postgres
      DB_HOST: db
      DB_PASSWORD: password123
      DB_NAME: items
      DB_PORT: 5432
      LOKI_HOST: loki
      LOKI_PORT: 3100
    networks:
      - items
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      loki:
        condition: service_started

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_healthy
      grafana:
        condition: service_started
      prom:
        condition: service_started
    networks:
      - items

  #### Observabilité ####

  # Exportateur des métriques de postgres
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.19.1
    environment:
      DATA_SOURCE_URI: "db:5432/postgres?sslmode=disable"
      DATA_SOURCE_USER: "postgres"
      DATA_SOURCE_PASS: "password123"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - items

  # Agrégat de logues
  loki:
    image: grafana/loki:3.7.1
    volumes:
      - loki_data:/loki
    networks:
      - items

  # Agrégat de métriques
  prom:
    image: prom/prometheus:v3.11.1
    volumes:
      - prom_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.route-prefix=/prom/"
      - "--web.external-url=http://localhost/prom/"
    networks:
      - items
    restart: unless-stopped

  # Visualisation de logues et métriques
  grafana:
    image: grafana/grafana-oss
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    networks:
      - items

volumes:
  postgres_data:
  loki_data:
  prom_data:
  grafana_data:

networks:
  items: