http {
    upstream api {
        server api:3000;
    }

    upstream grafana {
        server grafana:3000;
    }

    server {
        listen 80;

        location /health {
            proxy_pass http://api;

        }

        location /api {
            proxy_pass http://api;
        }

        location /grafana/ {
            proxy_set_header Host $http_host;
            proxy_pass http://grafana;
        }
    }
}

events {

}