http {
    limit_req_zone $binary_remote_addr zone=createlimit:10m rate=5r/m;

    upstream api {
        server api:3000;
    }

    upstream grafana {
        server grafana:3000;
    }

    upstream prom {
        server prom:9090;
    }

    server {
        listen 80;

        location /health {
            proxy_pass http://api;
        }

        location ~ /api/items/[0-9]* {
            limit_req zone=createlimit nodelay;
            proxy_pass http://api;
        }

        location /api {
            proxy_pass http://api;
        }

        location /grafana/ {
            proxy_set_header Host $http_host;
            proxy_pass http://grafana;
        }

        location /prom/ {
            proxy_set_header Host $http_host;
            proxy_pass http://prom;
        }
    }

    server {
        listen 8080;

        location = /stub_status {
            stub_status;
        }
    }
}

events {

}